deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: node-src
        path: build

    - name: Extract artifact
      run: |
        tar -xzf build/node-src.tar.gz -C build
        rm build/node-src.tar.gz

    - name: Install Railway CLI
      run: npm i -g @railway/cli@3.18.0

    - name: Authenticate with Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway login --token $RAILWAY_TOKEN

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        R_SERVICE: ${{ vars.RAILWAY_SERVICE }}
        R_ENV: ${{ vars.RAILWAY_ENV }}
      working-directory: build
      run: |
        SERVICE_FLAG=""
        ENV_FLAG=""
        if [ -n "${R_SERVICE}" ]; then SERVICE_FLAG="--service ${R_SERVICE}"; fi
        if [ -n "${R_ENV}" ]; then ENV_FLAG="--environment ${R_ENV}"; fi

        railway up $SERVICE_FLAG $ENV_FLAG